apiVersion: v1
kind: Service
metadata:
  name: vite-front-test-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-front-test-deploy
  namespace: default
  annotations:
    kubernetes.io/change-cause: init
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLebels:
      app: nginx
  template:
    metadata:
      name: vite-front-test-pod
      namepsace: default
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: nginx
          image: vite-front-test:latest
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent